find_file(LIBDISPATCH_INCLUDE_DIR NAMES dispatch/dispatch.h
  HINTS ${GCDPP_LIBDISPATCH_DIR}
  REQUIRED
  )

find_library(LIBDISPATCH_LIBRARY NAMES dispatch
  HINTS ${GCDPP_LIBDISPATCH_DIR}
  REQUIRED
  )
